server:
  port: 8080

# Spring Boot application configuration
spring:
  application:
    name: ai-rag-knowledge-base
  profiles:
    active: local
  # Datasource configuration
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ai-rag-knowledge-base
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: root
  # Spring AI configuration
  ai:
    model:
      chat: openai
      embedding: openai
    openai:
      base-url: http://localhost:11434
      api-key: empty
      chat:
        options:
          model: deepseek-r1:1.5b
      embedding:
        options:
          model: nomic-embed-text
          dimensions: 768
    vectorstore:
      pgvector:
        schema-name: public
        table-name: vector_store
        schema-validation: true
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 768
    mcp:
      client:
        enabled: true
        name: spring-ai-mcp-client
        version: 1.0.0
        initialized: true
        request-timeout: 30s
        type: sync # 客户端类型（SYNC 或 ASYNC）。所有客户端必须统一为同步或异步模式，不支持混合使用。
        root-change-notification: true
        toolcallback:
          enabled: true
        stdio:
          servers-configuration: classpath:/config/mcp-servers-config.json
#        sse:
#          connections:
#            mcp-server-csdn:
#              url: http://localhost:8101
#            mcp-server-weixin:
#              url: http://localhost:8102

# Redis configuration
redis:
  sdk:
    config:
      host: localhost
      port: 6379
      password: root
      pool-size: 10
      min-idle-size: 5
      idle-timeout: 30000
      connect-timeout: 5000
      retry-attempts: 3
      retry-interval: 1000
      ping-interval: 60000
      keep-alive: true

# Logging configuration
logging:
  level:
    root: info
    org.springframework: warn
    org.hibernate: warn
    com.lcx: debug
  config: classpath:logback-spring.xml