# 生产环境配置
# 可与传输模式组合使用：
# - java -jar mcp-server-csdn.jar --spring.profiles.active=prod,stdio
# - java -jar mcp-server-csdn.jar --spring.profiles.active=prod,sse

logging:
  level:
    root: WARN  # 生产环境：只输出 WARN 及以上日志，减少日志量
    okhttp3: WARN  # OkHttp 日志：只记录警告和错误
    retrofit2: INFO  # Retrofit HTTP 请求日志：INFO 级别
    org.springframework: WARN  # Spring 框架日志：只记录警告和错误
    org.springframework.ai: INFO  # Spring AI 日志：INFO 级别，记录关键操作
    com.lcx.mcp.server.csdn: INFO  # 应用日志：INFO 级别，记录关键业务信息

csdn:
  api:
    categories: ${CSDN_API_CATEGORIES}
    cookie: ${CSDN_API_COOKIE}
