# 开发环境配置
# 可与传输模式组合使用：
# - java -jar mcp-server-csdn.jar --spring.profiles.active=dev,stdio
# - java -jar mcp-server-csdn.jar --spring.profiles.active=dev,sse

logging:
  level:
    root: INFO
    okhttp3: INFO
    retrofit2: INFO
    org.springframework: INFO
    org.springframework.ai: DEBUG
    com.lcx.mcp.server.csdn: DEBUG  # 应用日志：DEBUG 级别，便于开发调试

csdn:
  api:
    categories:
    cookie: 
