# MCP Server CSDN - 通用配置
# 支持两种传输模式：
# 1. STDIO 模式：java -jar mcp-server-csdn.jar --spring.profiles.active=stdio
# 2. SSE 模式：  java -jar mcp-server-csdn.jar --spring.profiles.active=sse
# 
# 其他环境配置：local, dev, prod

spring:
  application:
    name: mcp-server-csdn
  profiles:
    active: sse,local
  ai:
    mcp:
      server:
        enabled: true
        name: ${spring.application.name}
        version: 0.0.1
