# 生产环境配置
server:
  port: 8081

logging:
  # 日志级别配置：生产环境使用 INFO/WARN 级别，减少日志输出，提升性能
  level:
    root: WARN
    org.springframework: WARN
    com.lcx.mcp.server.csdn: INFO  # 应用日志使用 INFO，只记录关键信息

csdn:
  api:
    categories: ${CSDN_CATEGORIES:}
    cookie: ${CSDN_COOKIE:}

