server:
  port: 8080

spring:
  application:
    name: ai-rag-knowledge-base
  profiles:
    active: dev # 默认启用开发环境
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://118.196.28.78:15432/ai-rag-knowledge-base
    type: com.zaxxer.hikari.HikariDataSource
    username: admin
    password: admin321
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        enabled: true
        options:
          model: deepseek-r1:1.5b
      embedding:
        options:
          num-batch: 512
        model: nomic-embed-text

redis:
  sdk:
    config:
      host: 118.196.28.78
      port: 16379
      password: admin321
      pool-size: 10
      min-idle-size: 5
      idle-timeout: 30000
      connect-timeout: 5000
      retry-attempts: 3
      retry-interval: 1000
      ping-interval: 60000
      keep-alive: true

logging:
  level:
    root: debug
  config: classpath:logback-spring.xml