server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

spring:
  application:
    name: mcp-server-systemInfo
  profiles:
    active: prod
  ai:
    mcp:
      server:
        enabled: true
        stdio: true
        name: ${spring.application.name}
        version: 0.0.1
        type: async
        instructions: "This server provides system information tools"
  main:
    # 关闭 Spring Boot 启动横幅，避免向 stdout 输出非 JSON 内容
    banner-mode: off
    # STDIO 模式必须设置为 none，不启动 Web 容器
    web-application-type: none

logging:
  # 关闭控制台日志输出，保证 stdout 只用于 MCP JSON-RPC 通信
  pattern:
    console:
  # 文件日志配置：所有日志输出到文件，用于调试和问题排查
  file:
    name: data/log/mcp/${spring.application.name}.log
